### ISSUE TITLE
尝试修改parameters.json的model和Reverse-proxy失败

### ISSUE THREAD

**Issue by Hammerstein3217** [Euyug/Mirai-Gpt-Plugin#3]
我尝试将parameters.json里的model替换成GPT4（gpt-4-1106-preview），把反向代理改为本地代理127.0.0.1:1080
替换完成后我重新启动Mirai机器人，启动后parameters.json又被覆写回了原来的参数
"model": "gpt-3.5-turbo",
"Reverse-proxy":"api.openai-proxy.com"

请问是否是在哪儿操作不对导致的？

**Comment by Euyug** [comment]
[Uploading gptbot-1.2.mirai.zip…]()

**Comment by Euyug** [comment]
> 我尝试将parameters.json里的model替换成GPT4（gpt-4-1106-preview），把反向代理改为本地代理127.0.0.1:1080 替换完成后我重新启动Mirai机器人，启动后parameters.json又被覆写回了原来的参数 "model": "gpt-3.5-turbo", "Reverse-proxy":"api.openai-proxy.com"
> 
> 请问是否是在哪儿操作不对导致的？
启动自动覆盖了 现在改掉了，但是反向代理要你有服务器代理openai的api地址才能用，你用的那个本地是正向代理

**Comment by Euyug** [comment]
> > 我尝试将parameters.json里的model替换成GPT4（gpt-4-1106-preview），把反向代理改为本地代理127.0.0.1:1080 替换完成后我重新启动Mirai机器人，启动后parameters.json又被覆写回了原来的参数 "model": "gpt-3.5-turbo", "Reverse-proxy":"api.openai-proxy.com"
> > 请问是否是在哪儿操作不对导致的？
> > 启动自动覆盖了 现在改掉了，但是反向代理要你有服务器代理openai的api地址才能用，你用的那个本地是正向代理

[gptbot-1.2.mirai.zip](https://github.com/Euyug/Mirai-Gpt-Plugin/files/13612292/gptbot-1.2.mirai.zip)

**Comment by Hammerstein3217** [comment]
> > 我尝试将parameters.json里的model替换成GPT4（gpt-4-1106-preview），把反向代理改为本地代理127.0.0.1:1080 替换完成后我重新启动Mirai机器人，启动后parameters.json又被覆写回了原来的参数 "model": "gpt-3.5-turbo", "Reverse-proxy":"api.openai-proxy.com"
> > 请问是否是在哪儿操作不对导致的？
> > 启动自动覆盖了 现在改掉了，但是反向代理要你有服务器代理openai的api地址才能用，你用的那个本地是正向代理

OKOK，那代理地址我就先不换了

**Comment by Hammerstein3217** [comment]
替换成楼里的[gptbot-1.2.mirai.zip](https://github.com/Euyug/Mirai-Gpt-Plugin/files/13612292/gptbot-1.2.mirai.zip)后成功，现在不会被覆盖了，感谢！
